package microservice;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.RETURNS_MOCKS;
import static org.mockito.Mockito.when;

import org.apache.catalina.connector.Response;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;

public class MainControllerTest {
	  
	//private MainController addNewArticle;
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	//private StockRepository stockRepository;
	
		private static final Integer ARTICLE = 100;
		private static final Integer STOCK = 1;
		
		
		@Test
		public void verifyitworks() {
			MainController mainController = new MainController();
			String response  = mainController.addNewArticle(ARTICLE, STOCK);
			assertEquals("Stock succesfuly saved for article = " + 100, response);
		
		
			
		}
	
		}
		
