package microservice;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import microservice.Stock;
import microservice.StockRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private StockRepository stockRepository;
	
	@GetMapping(path="/addArticle") // Map ONLY GET Requests
	public @ResponseBody String addNewArticle (@RequestParam Integer article
			, @RequestParam Integer stock) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Stock n = new Stock();
		n.setArticle(article);
		n.setStock(stock);
		stockRepository.save(n);
		return "Stock succesfuly saved for article = " + article;
	}
	
	@GetMapping(path="/getArticle")
	public @ResponseBody Iterable<Stock> getAllArticles() {
		// This returns a JSON or XML with the users
		Iterable<Stock> response = stockRepository.findAll();
		return response; 
	}
	
	
}
